name: Generate Snake

on:
schedule:
- cron: "0 0 * * *"
workflow_dispatch:

jobs:
generate:
runs-on: ubuntu-latest

```
steps:
  - name: Generate snake animation
    uses: Platane/snk@v3
    with:
      github_user_name: vidhiomar
      outputs: |
        dist/snake.svg?palette=github-dark
        dist/snake2.svg?palette=github-dark&color_snake=#ff00ff

  - name: Push snake to output branch
    uses: peaceiris/actions-gh-pages@v3
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./dist
      publish_branch: output
```
